### ISSUE TITLE
 develop 브랜치 파일 구조 문제

### ISSUE THREAD

**Issue by costudying** [JavaJo-SemiProject/DASi-Project#128]
## Description
* * *
- DASI 파일이 새로 만들어진 문제
- 파일 구조가 변경되는 문제
- 파일 구조 변경으로 인한 충돌 문제

## To-do
* * *
- [x] 파일구조 재설정 후 PR 테스트 
- [ ] 팀 파일구조 재설정
- [ ] 각 팀원 브랜치 재설정
- [ ] 파트별 파일 취합
